[package]
name = "escposify"
version = "0.1.0"
description = "A ESC/POS driver for Rust"
readme = "README.md"
repository = "https://github.com/local-group/escposify-rs"
license = "MIT"
authors = ["Qian Linfeng <thewawar@gmail.com>"]


[dependencies]
encoding = "0.2.32"
byteorder = "0.5.1"
image = "0.9.0"
tempfile = "2.1.3"
